use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct OrderbookMessage {
    pub hotime: String, // 호가시간

    // 1~10호가
    pub offerho1: f64,
    pub bidho1: f64,
    pub krx_offerrem1: i64,
    pub nxt_offerrem1: i64,
    pub unt_offerrem1: i64,
    pub krx_bidrem1: i64,
    pub nxt_bidrem1: i64,
    pub unt_bidrem1: i64,

    pub offerho2: f64,
    pub bidho2: f64,
    pub krx_offerrem2: i64,
    pub nxt_offerrem2: i64,
    pub unt_offerrem2: i64,
    pub krx_bidrem2: i64,
    pub nxt_bidrem2: i64,
    pub unt_bidrem2: i64,

    pub offerho3: f64,
    pub bidho3: f64,
    pub krx_offerrem3: i64,
    pub nxt_offerrem3: i64,
    pub unt_offerrem3: i64,
    pub krx_bidrem3: i64,
    pub nxt_bidrem3: i64,
    pub unt_bidrem3: i64,

    pub offerho4: f64,
    pub bidho4: f64,
    pub krx_offerrem4: i64,
    pub nxt_offerrem4: i64,
    pub unt_offerrem4: i64,
    pub krx_bidrem4: i64,
    pub nxt_bidrem4: i64,
    pub unt_bidrem4: i64,

    pub offerho5: f64,
    pub bidho5: f64,
    pub krx_offerrem5: i64,
    pub nxt_offerrem5: i64,
    pub unt_offerrem5: i64,
    pub krx_bidrem5: i64,
    pub nxt_bidrem5: i64,
    pub unt_bidrem5: i64,

    pub offerho6: f64,
    pub bidho6: f64,
    pub krx_offerrem6: i64,
    pub nxt_offerrem6: i64,
    pub unt_offerrem6: i64,
    pub krx_bidrem6: i64,
    pub nxt_bidrem6: i64,
    pub unt_bidrem6: i64,

    pub offerho7: f64,
    pub bidho7: f64,
    pub krx_offerrem7: i64,
    pub nxt_offerrem7: i64,
    pub unt_offerrem7: i64,
    pub krx_bidrem7: i64,
    pub nxt_bidrem7: i64,
    pub unt_bidrem7: i64,

    pub offerho8: f64,
    pub bidho8: f64,
    pub krx_offerrem8: i64,
    pub nxt_offerrem8: i64,
    pub unt_offerrem8: i64,
    pub krx_bidrem8: i64,
    pub nxt_bidrem8: i64,
    pub unt_bidrem8: i64,

    pub offerho9: f64,
    pub bidho9: f64,
    pub krx_offerrem9: i64,
    pub nxt_offerrem9: i64,
    pub unt_offerrem9: i64,
    pub krx_bidrem9: i64,
    pub nxt_bidrem9: i64,
    pub unt_bidrem9: i64,

    pub offerho10: f64,
    pub bidho10: f64,
    pub krx_offerrem10: i64,
    pub nxt_offerrem10: i64,
    pub unt_offerrem10: i64,
    pub krx_bidrem10: i64,
    pub nxt_bidrem10: i64,
    pub unt_bidrem10: i64,

    pub krx_totofferrem: i64,
    pub nxt_totofferrem: i64,
    pub unt_totofferrem: i64,
    pub krx_totbidrem: i64,
    pub nxt_totbidrem: i64,
    pub unt_totbidrem: i64,

    pub krx_donsigubun: String,
    pub nxt_donsigubun: String,
    pub shcode: String,
    pub alloc_gubun: String,
    pub volume: i64,

    pub krx_midprice: f64,
    pub krx_offermidsumrem: i64,
    pub krx_bidmidsumrem: i64,
    pub nxt_midprice: f64,
    pub nxt_offermidsumrem: i64,
    pub nxt_bidmidsumrem: i64,
    pub krx_midsumrem: i64,
    pub krx_midsumremgubun: i64,
    pub nxt_midsumrem: i64,
    pub nxt_midsumremgubun: String,
    pub ex_shcode: String,
}
